### ISSUE TITLE
CS 259 Tracker

### ISSUE THREAD

**Issue by zhaochenyang20** [zhaochenyang20/Awesome-ML-SYS-Tutorial#110]
# 课程评分

- 讨论参与 20 分
1. 参与课堂讨论，主要在 canvas 上
2. 参与课堂

- 小型项目 15 分
1. GPU 并行处理机器学习内核
2. ML accelerator simulator

- Pre 25 分
1. 2 人 pre 一篇 paper

- Open-Ended Group Project 40 分
1. 2 人做一个 project

**Comment by zhaochenyang20** [comment]
28 号 mini project deadline；

**Comment by zyt600** [comment]
你搜索邮件关键词“tetracosa”可以找到注册课程机器账号的教程：Hi All -- you can sign up for the tetracosa machine by doing the following from the campus network:

ssh [account@tetracosa.cs.ucla.edu]

Password: xxxxx

ssh之后注册用户名密码

**Comment by zyt600** [comment]
关于怎么编译，在你装好cuda一系列东西后，nvcc conv1.cu（文件名） -lcudnn -o conv1（可执行文件名）就行，这里的-lcudnn如果不成功，你就问gpt缺了什么

**Comment by zyt600** [comment]
看看现在的ci，问cursor找测量分数的test，看在做什么
设计、调研需要加哪些nightly benchmark，vision、llm
math、aime、mmupro
怎么profile 系统利用率提高了

**Comment by zyt600** [comment]
## test_awq：
- 验证量化后的MoE模型在MMLU多任务语言理解基准测试中的表现
- 检查模型得分是否超过0.64的阈值
## test_block_int8
- 验证自定义的`fused_moe`函数与参考实现`torch_w8a8_block_int8_moe`在数值精度上的一致性
- 测试混合专家模型在8位量化下的正确性

## test_bnb
1. 视觉语言模型(VLM)测试 (TestVisionModel类)
- 测试了6个视觉语言模型，包括Qwen、Llama和Gemma等系列
- 测试内容包括：
  * 单张图片描述生成
  * 多轮对话测试
  * 多张图片混合描述
  * 混合批量测试(不同图片交替处理)
- 使用OpenAI API风格的接口进行测试
- 验证了模型能正确识别图片内容(如识别"男人"、"出租车"、"熨烫"等元素)
- 检查了返回结果的结构完整性(如token使用统计、响应ID等)

2. 语言模型测试 (TestLanguageModel类)
- 测试了4个语言模型，包括Qwen、Llama和Gemma等系列
- 主要测试MMLU(大规模多任务语言理解)能力
- 评估模型在32个示例上的表现
- 要求得分高于0.3才算通过

## test_double_sparsity
- 验证使用Double Sparsity配置的Llama-3.1-8B-Instruct模型在MMLU评估任务中的表现

## test_fp8_kernel
这个Python文件测试了两个FP8(8位浮点数)量化相关函数的正确性

## test_gptqmodel_dynamic
测试文件主要测试了GPTQ量化模型的两个不同实现方式：标准GPTQ内核和Marlin内核

## test_int8_kernel
测试了使用INT8量化的混合专家

## test_local_attn
- 验证FlashAttention3本地注意力机制在GSM8K数学推理任务上的准确性

## test_modelopt
- 测试FP8模型量化后的精度准确性
- 使用MMLU评估集进行量化模型的质量验证
- 检查量化后的模型评分是否达到预期阈值(0.64)

## test_moe_deepep_eval_accuracy_large
测试了一个基于MoE架构的DeepEP模型在两个不同任务上的评估准确率

## test_moe_eval_accuracy_large
测试了一个混合专家模型在多个评估任务上的准确性表现

## test_nightly_gsm8k_eval_amd
测试了多个语言模型在GSM8K（数学推理）任务上的性能表现，属于夜间自动化测试套件的一部分

## test_nightly_gsm8k_eval
测试了多个语言模型在GSM8K（数学推理）任务上的性能表现

## test_vllm_dependency
测试了多个量化模型在GSM8K数学推理任务上的性能表现
   - 验证多个量化模型在MGSM英语数学推理任务上的准确性
   - 检查模型得分是否达到预设的阈值标准

**Comment by zhaochenyang20** [comment]
1. 这些 test 里面，可以调研下，哪些是目前在 nightly CI 里面的，应该目前是有 nightly CI 的，但我不确定在哪儿；然后，哪些是在逐 commit CI 的；具体列出 nightly CI 覆盖的模型 + 场景（比如是不是量化模型） + benchmark，然后逐 commit CI 的覆盖情况；
2. 很多 test 是写了，但是未必加到了 CI 里面，我们得分清楚；

**Comment by zyt600** [comment]
test/srt/run_suite.py已经列出了所有per commit、nightly的ci；在.github/workflows里不同的workflow会调用不同的run_suite中的suite
# nightly的是test_nightly_gsm8k_eval.py
是一个用于评估大语言模型在 GSM8K 数学问题数据集上表现的测试文件，每个模型都有预设的评分阈值，用于判断模型表现是否达标。
## 模型覆盖情况：
### 基础模型：
Llama-3.1-8B-Instruct
Mistral-7B-Instruct-v0.3
DeepSeek-Coder-V2-Lite-Instruct
Gemma-2-27b-it
Llama-3.1-70B-Instruct
Mixtral-8x7B-Instruct-v0.1
Qwen2-57B-A14B-Instruct
### 量化模型（FP8）：
Meta-Llama-3.1-8B-Instruct-FP8
Mistral-7B-Instruct-v0.3-FP8
DeepSeek-Coder-V2-Lite-Instruct-FP8
Gemma-2-2b-it-FP8
Meta-Llama-3.1-70B-Instruct-FP8
Mixtral-8x7B-Instruct-v0.1-FP8
Qwen2-72B-Instruct-FP8
Qwen2-57B-A14B-Instruct-FP8
## 测试场景：
模型部署方式：
TP1（单张卡）
TP2（两张卡并行）
FP8量化版本
非量化版本
Benchmark：
## 使用GSM8K数据集进行测试
每个模型都有对应的分数阈值要求：

# nightly-amd包含test_nightly_gsm8k_eval_amd.py，和上述差不多

# per-commit的有
    "per-commit": [
        TestFile("models/lora/test_lora.py", 76),
        TestFile("models/lora/test_lora_backend.py", 99),
        TestFile("models/lora/test_multi_lora_backend.py", 60),
        TestFile("models/test_embedding_models.py", 184),
        TestFile("models/test_clip_models.py", 52),
        TestFile("models/test_compressed_tensors_models.py", 42),
        TestFile("models/test_generation_models.py", 103),
        TestFile("models/test_gme_qwen_models.py", 45),
        # TestFile("models/test_grok_models.py", 60),  # Disabled due to illegal memory access
        TestFile("models/test_qwen_models.py", 82),
        TestFile("models/test_reward_models.py", 132),
        TestFile("models/test_vlm_models.py", 317),
        TestFile("test_abort.py", 51),
        TestFile("test_block_int8.py", 22),
        TestFile("test_create_kvindices.py", 2),
        TestFile("test_chunked_prefill.py", 285),
        TestFile("test_eagle_infer.py", 584),
        TestFile("test_ebnf_constrained.py", 108),
        TestFile("test_embedding_openai_server.py", 141),
        TestFile("test_eval_fp8_accuracy.py", 303),
        TestFile("test_fa3.py", 376),
        TestFile("test_fim_completion.py", 40),
        TestFile("test_fp8_kernel.py", 8),
        TestFile("test_function_calling.py", 60),
        TestFile("test_fused_moe.py", 30),
        TestFile("test_hicache.py", 116),
        TestFile("test_hicache_mla.py", 254),
        TestFile("test_hidden_states.py", 55),
        TestFile("test_int8_kernel.py", 8),
        TestFile("test_input_embeddings.py", 38),
        TestFile("test_json_constrained.py", 98),
        TestFile("test_large_max_new_tokens.py", 41),
        TestFile("test_metrics.py", 32),
        TestFile("test_mla.py", 242),
        TestFile("test_mla_deepseek_v3.py", 221),
        TestFile("test_mla_int8_deepseek_v3.py", 389),
        TestFile("test_mla_flashinfer.py", 395),
        TestFile("test_mla_fp8.py", 153),
        TestFile("test_flashmla.py", 300),
        TestFile("test_no_chunked_prefill.py", 108),
        TestFile("test_no_overlap_scheduler.py", 216),
        TestFile("test_openai_server.py", 149),
        TestFile("test_penalty.py", 41),
        TestFile("test_page_size.py", 60),
        TestFile("test_pytorch_sampling_backend.py", 66),
        TestFile("test_radix_attention.py", 167),
        TestFile("test_reasoning_content.py", 89),
        TestFile("test_enable_thinking.py", 70),
        TestFile("test_regex_constrained.py", 64),
        TestFile("test_release_memory_occupation.py", 44),
        TestFile("test_request_length_validation.py", 31),
        TestFile("test_retract_decode.py", 54),
        TestFile("test_server_args.py", 1),
        TestFile("test_skip_tokenizer_init.py", 117),
        TestFile("test_srt_engine.py", 261),
        TestFile("test_srt_endpoint.py", 130),
        TestFile("test_torch_compile.py", 76),
        TestFile("test_torch_compile_moe.py", 172),
        TestFile("test_torch_native_attention_backend.py", 123),
        TestFile("test_torchao.py", 70),
        TestFile("test_triton_attention_kernels.py", 4),
        TestFile("test_triton_attention_backend.py", 134),
        TestFile("test_triton_moe_channel_fp8_kernel.py", 25),
        TestFile("test_update_weights_from_disk.py", 114),
        TestFile("test_update_weights_from_tensor.py", 48),
        TestFile("test_vertex_endpoint.py", 31),
        TestFile("test_vision_chunked_prefill.py", 175),
        TestFile("test_vlm_accuracy.py", 60),
        TestFile("test_vision_openai_server_a.py", 700),
        TestFile("test_vision_openai_server_b.py", 700),
        TestFile("test_w8a8_quantization.py", 46),
        TestFile("models/lora/test_lora_cuda_graph.py", 250),
    ],
    "per-commit-amd": [
        TestFile("test_mla.py", 242),
        TestFile("test_mla_deepseek_v3.py", 221),
        TestFile("test_torch_compile.py", 76),
        TestFile("test_torch_compile_moe.py", 172),
    ],
    "per-commit-2-gpu": [
        TestFile("models/lora/test_lora_tp.py", 116),
        TestFile("test_data_parallelism.py", 73),
        TestFile("test_dp_attention.py", 137),
        TestFile("test_mla_tp.py", 170),
        TestFile("test_moe_ep.py", 181),
        TestFile("test_patch_torch.py", 19),
        TestFile("test_update_weights_from_distributed.py", 103),
        TestFile("test_verl_engine.py", 64),
    ],
    "per-commit-2-gpu-amd": [
        TestFile("test_mla_tp.py", 170),
    ],
    "per-commit-4-gpu": [
        TestFile("test_local_attn.py", 250),
        TestFile("test_pp_single_node.py", 150),
    ],
    "per-commit-8-gpu": [
        # Disabled deepep tests temporarily because it takes too much time.
        # TODO: re-enable them after reducing the test time with compilation cache and smaller models.
        # TestFile("test_deepep_intranode.py", 50),
        # TestFile("test_deepep_low_latency.py", 50),
        # TestFile("test_moe_deepep_eval_accuracy_large.py", 250),
        # TestFile("test_disaggregation.py", 210), # disabled since we have different_tp test
        TestFile("test_disaggregation_different_tp.py", 210),
        TestFile("test_full_deepseek_v3.py", 250),
    ],
    "per-commit-8-gpu-amd": [
        TestFile("test_full_deepseek_v3.py", 250),
    ],

**Comment by zhaochenyang20** [comment]
1. 更新 nightly 的模型，有的模型过期了；简单来说，你可以查查这些模型的发布时间，然后看看有没有同系列更新的模型，比如 Qwen2 可以直接换为 Qwen 2.5，llama 3.1 可以换为 llama 3.2；这个需要自己建立一个 sense，就是什么模型是广受好评的重要模型。其实也简单，直接看 huggingface 下载量就知道了。
2. 添加 Reasoning 模型的测试：具体来说，测试 Qwen qwq 32B 模型和 xiaomi MiMo 的最小的模型，测试的 benchmark 选择 AIME 2025 pass@1。需要调研下如何测试 AIME 2025，要写到 CI 里面。
3. 添加 VLM 的测试：这里用 Qwen 2.5 VL 最好，具体的 benchmark 可以去 VLM 群里问问，但我感觉大概率是 MMMU-Pro。
4. 添加 MOE 模型的测试：其实上文有一些 MOE 模型，比如这个 Mixtral-8x7B-Instruct-v0.1，但是可以再找找 popular 的 MOE 模型，最好找个 MOE LLM 和 MOE LLM，分别添加到对应的测试里面；
5. 思考如何提高资源利用率，这个我会和 team mates 沟通，看看我们能够读取 CI 机器到什么情况。

**Comment by zhaochenyang20** [comment]
1. 模型上：大概率 2 * H20 是个非常完整的覆盖了，你可以预估 2 * H20 可以跑下 40B 的模型，这对大部分模型 `tp_size = 2` 都可以启动了；
2. 大概率模型跑一次和官方的差距不大，差 5 个点以上的就有严重问题了；不过，注意，官方的 report 会报道一系列的模型，得严格找到你测的模型，比如 `llama 3.2 8B` 和 `llama 3.2 8B Instruct` 是两个完全不同的模型，一定要找准分数；
3. 网络的话，问问桂哥，或者还不行你让我去联系 yanbo；

**Comment by zhaochenyang20** [comment]
## LLM
 
- `Llama-3.3-70B-Instruct` 去找下有没有 FP8 的，比如 redhat ai 的，这样 tp 2 一定可以跑下来，跑不下来再去问 😂
- "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8": 0.83, 删了，nobody fucking care；
- "RedHatAI/Mistral-7B-Instruct-v0.3-FP8": 0.54, 删了；
- "RedHatAI/DeepSeek-Coder-V2-Lite-Instruct-FP8": 0.84, 这个也删了，因为 dpsk 的分数会有单独的 per commit CI；
- “"deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct": 0.85, # TODO: V3” 删了；
-  "moonshotai/Moonlight-16B-A3B-Instruct": 0.00, # TODO: fix this 删了；

- Qwen 2.5 要加上，建议测试一个 30B 左右的 BF16 和 72B 的 FP8；

## VLM

 MMMU-Pro 如何测试；

- Qwen/Qwen2.5-VL-32B-Instruct
- Qwen/Qwen2.5-VL-72B-Instruct-AWQ
- OpenGVLab/InternVL3-78B 得找个量化的来测试
- OpenGVLab/InternVL3-38B

## MOE

- "mistralai/Mixtral-8x7B-Instruct-v0.1": 0.64,
- "Qwen/Qwen3-235B-A22B": 0.86 和 "mistralai/Mixtral-8x7B-Instruct-v0.1": 0.64 测不了，但是留着，先 skip 了；

## DPSK

我们不做，但是列出来；

**Comment by zhaochenyang20** [comment]
```yaml
# The full test workflow will be triggered daily at midnight UTC,
# or during any 5-minute interval after midnight UTC, provided that
# the external API returns `true` and the test has not already run
# on that day.
  
# If the external API does not return `true` on a given day,
# a test will be forcibly triggered at midnight UTC, regardless
# of the API's status (again, if the test has not already run that day).

name: Nightly Test

on:
  schedule:
    - cron: '*/5 * * * *' 
    - cron: '0 0 * * *'    
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

concurrency:
  group: nightly-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-test:
    if: github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request'
    runs-on: 2-gpu-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Check last run date
        id: check-last-run
        run: |
          LAST_RUN_FILE=".github/last_run.txt"
          CURRENT_DATE=$(date -u +%Y-%m-%d)
          LAST_RUN_DATE=""
          
          if [ -f "$LAST_RUN_FILE" ]; then
            LAST_RUN_DATE=$(cat "$LAST_RUN_FILE")
          fi
          
          if [ "$LAST_RUN_DATE" = "$CURRENT_DATE" ]; then
            echo "Workflow already ran today ($CURRENT_DATE). Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Poll endpoint
        id: poll-endpoint
        if: steps.check-last-run.outputs.skip == 'false'
        run: |
          RESPONSE=$(curl -s http://xxxx:xxxx | jq -r '.result')
          echo "API response: $RESPONSE"
          if [ "$RESPONSE" = "true" ]; then
            echo "trigger=true" >> $GITHUB_OUTPUT
          else
            echo "trigger=false" >> $GITHUB_OUTPUT
          fi
        env:
          # We mask the actual endpoint here for security reasons
          ENDPOINT: http://xxxx:xxxx

      - name: Check if midnight run is needed
        id: check-midnight
        if: steps.check-last-run.outputs.skip == 'false' && steps.poll-endpoint.outputs.trigger != 'true'
        run: |
          CURRENT_HOUR=$(date -u +%H)
          CURRENT_MINUTE=$(date -u +%M)
          if [ "$CURRENT_HOUR" = "00" ] && [ "$CURRENT_MINUTE" = "00" ]; then
            echo "Midnight run triggered."
            echo "trigger=true" >> $GITHUB_OUTPUT
          else
            echo "Not midnight. No trigger."
            echo "trigger=false" >> $GITHUB_OUTPUT
          fi

      - name: Update last run date
        if: (steps.poll-endpoint.outputs.trigger == 'true' || steps.check-midnight.outputs.trigger == 'true') && steps.check-last-run.outputs.skip == 'false'
        run: |
          CURRENT_DATE=$(date -u +%Y-%m-%d)
          echo "$CURRENT_DATE" > .github/last_run.txt
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github/last_run.txt
          git commit -m "Update last run date to $CURRENT_DATE"
          git push

      - name: Install dependencies
        if: (steps.poll-endpoint.outputs.trigger == 'true' || steps.check-midnight.outputs.trigger == 'true') && steps.check-last-run.outputs.skip == 'false'
        run: |
          bash scripts/ci_install_dependency.sh

      - name: Run test
        if: (steps.poll-endpoint.outputs.trigger == 'true' || steps.check-midnight.outputs.trigger == 'true') && steps.check-last-run.outputs.skip == 'false'
        timeout-minutes: 120
        run: |
          cd test/srt
          python3 run_suite.py --suite nightly --timeout-per-file 3600
```
